FUNCTION ZEBIZ_UPDATECUSTOMERPAYMETHOD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(CUSTOMERPRM) TYPE  ZEBIZ_CHARGEPAYMENT_METHOD_PRO
*"     REFERENCE(CUSTOMER_ID) TYPE  /ASU/CHAR72
*"  EXPORTING
*"     REFERENCE(SUCCESSS) TYPE  /ASU/ADHOC_STEP
*"     REFERENCE(UPDATE_CUSTOMER_PAYMENT_METHOD) TYPE  XSDBOOLEAN
*"----------------------------------------------------------------------
  DATA: EXC TYPE REF TO CX_ROOT.
  DATA: MSG TYPE STRING.
  DATA: PROXY_TEST TYPE REF TO ZEBIZ_CHARGECO_IE_BIZ_SERVICE,
        SECURITY   TYPE ZEBIZ_CHARGESECURITY_TOKEN.


  DATA: CWA        TYPE ZEBIZ_CONFIG
        .
  SELECT SINGLE * FROM ZEBIZ_CONFIG INTO CWA
    .

  TRY.
      DATA:
        INPUT          TYPE ZEBIZ_CHARGEIE_BIZ_SERVICE_U20,
        OUTPUT         TYPE ZEBIZ_CHARGEIE_BIZ_SERVICE_U19,
        TOKEN_INPUT    TYPE ZEBIZ_CHARGEIE_BIZ_SERVICE_G45,
        TOKEN_OUTPUT   TYPE ZEBIZ_CHARGEIE_BIZ_SERVICE_G44,
        CUSTOMER_TOKEN TYPE STRING.
      IF PROXY_TEST IS NOT BOUND.
        CREATE OBJECT PROXY_TEST
          EXPORTING
            LOGICAL_PORT_NAME = 'EBIZ'.
      ENDIF.
      SECURITY-SECURITY_ID = CWA-SECURITYKEY.
      TOKEN_INPUT-SECURITY_TOKEN = SECURITY.
      TOKEN_INPUT-CUSTOMER_ID = CUSTOMER_ID.
      try.
      CALL METHOD PROXY_TEST->GET_CUSTOMER_TOKEN
        EXPORTING
          INPUT  = TOKEN_INPUT
        IMPORTING
          OUTPUT = TOKEN_OUTPUT.
        CATCH CX_AI_SYSTEM_FAULT INTO EXC.
           msg = exc->GET_TEXT( ).
       CONCATENATE 'Error in GET_CUSTOMER_TOKEN :' msg into msg.
          CALL FUNCTION 'ZEBIZ_LOGFILE'
  EXPORTING
    LOGTEXT = msg.
  .
          MESSAGE  W398(00) WITH MSG.
*CATCH zcx_zsqrt_exception.
        CATCH CX_AI_APPLICATION_FAULT INTO EXC.
          msg = exc->GET_TEXT( ).
       CONCATENATE 'Error in GET_CUSTOMER_TOKEN :' msg into msg.
          CALL FUNCTION 'ZEBIZ_LOGFILE'
  EXPORTING
    LOGTEXT = msg.
  .
          MESSAGE  W398(00) WITH MSG.
      ENDTRY.
      CUSTOMER_TOKEN = TOKEN_OUTPUT-GET_CUSTOMER_TOKEN_RESULT.
*

*     there is one input value for this service call for user id

      INPUT-SECURITY_TOKEN = SECURITY.
      INPUT-CUSTOMER_TOKEN = CUSTOMER_TOKEN.
      INPUT-PAYMENT_METHOD_PROFILE = CUSTOMERPRM.

*     call the method (web service call) you can use the pattern to generate the code if you wish
      CALL METHOD PROXY_TEST->UPDATE_CUSTOMER_PAYMENT_METHOD
        EXPORTING
          INPUT  = INPUT
        IMPORTING
          OUTPUT = OUTPUT.

*     process the output
      UPDATE_CUSTOMER_PAYMENT_METHOD = OUTPUT-UPDATE_CUSTOMER_PAYMENT_METHOD.
      SUCCESSS = 'X'.
    CATCH CX_AI_SYSTEM_FAULT INTO EXC.
    msg = exc->GET_TEXT( ).
       CONCATENATE 'Error in UPDATE_CUSTOMER_PAYMENT_METHOD :' msg into msg.
          CALL FUNCTION 'ZEBIZ_LOGFILE'
  EXPORTING
    LOGTEXT = msg.
  .
      MESSAGE  W398(00) WITH MSG.
      SUCCESSS = 'Y'.
*CATCH zcx_zsqrt_exception.
    CATCH CX_AI_APPLICATION_FAULT INTO EXC.
     msg = exc->GET_TEXT( ).
       CONCATENATE 'Error in UPDATE_CUSTOMER_PAYMENT_METHOD :' msg into msg.
          CALL FUNCTION 'ZEBIZ_LOGFILE'
  EXPORTING
    LOGTEXT = msg.
  .
      MESSAGE  W398(00) WITH MSG.
      SUCCESSS = 'Y'.
*      MESSAGE msg TYPE 'E'.
  ENDTRY.
ENDFUNCTION.
